### ISSUE TITLE
[BUG] `Image.network` can cause memory leak, if link to GIF was passed

### ISSUE THREAD

**Issue by dan63047** [dan63047/TetraStats#81]
**Describe the bug**
Apparently, if you leave Tetra Stats open on a different virtual desktop with `Image.network` which renders "GIF", it will slowly eat all memory. Funny enough, if you collapse window first, and then go to different virtual desktop, nothing will happen.

**How to reproduce**
1. Open `osk` profile (the only one, that has GIF banner, which is `https://tetr.io/user-content/banners/5e32fc85ab319c2ab1beb07c.jpg?rv=1628366386763`)
2. Move window to a different virtual desktop and wait...
3. After few minutes amount of virtual memory used will drastically increases. (Wait longer and your system will become unusable)
4. Come back to virtual desktop with Tetra Stats and memory leak will disappear.

**Expected behavior**
It shouldn't eat that much memory.

**Screenshots**
![Screenshot of RAM graph](https://github.com/dan63047/TetraStats/assets/44553627/9bc55e28-f418-4bae-b837-0dfcad168402)

**Technical information**
 - Platform: Linux, Debian 12, XFCE 4, X11
 - App Version: 1.4.1

**Additional context**
It's pretty much can be Flutter issue, potentially can be related: [1](https://github.com/flutter/flutter/issues/84565) although i'm not sure since 1. different platform 2. Is my jpg a gif?

Need to investigate this somehow...

**Comment by dan63047** [comment]
Flutter memory chart fails to show this...
![image](https://github.com/dan63047/TetraStats/assets/44553627/8ac6cb78-947e-445e-82d5-6d68f07bde29)

**Comment by Katamithetaka** [comment]
Haha isn't it great how osk sends a gif in a url .jpg
![image](https://github.com/user-attachments/assets/3c05a810-74da-4e09-8157-180d683f0189)
As all great systems do, obviously osk server ignores the Accept header so you can't even make it send a jpg by putting a header
![image](https://github.com/user-attachments/assets/971ef6d1-84f6-4de0-ae88-f16df6af993b)
Obviously as this is AS awesome osk sends image/jpeg as content type EVEN THOUGH it's a gif.
Your best bet may be to check to the magic bytes at the beginning of the image 
GIF87a: 47 49 46 38 37 61 (Hexadecimal)
GIF89a: 47 49 46 38 39 61 (Hexadecimal)
And if it's those it's *likely* to be a gif in which case you should treat it differently (Maybe download the whole image, get the first frame and then display that?)

**Comment by Katamithetaka** [comment]
Related solution to draw the first frame only: https://stackoverflow.com/questions/74670994/flutter-gif-image-to-still-image

**Comment by dan63047** [comment]
Thank you, Taka. Appreciate you so much!
